services:

  mysql_banquee:
    container_name: mysql_banquee
    image: mysql:8.0.33
    command:
      mysqld --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --sql_mode=""
    restart: always
    environment:
      MYSQL_DATABASE: banquee_gesse
      MYSQL_USER: banquee
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  node_express_api:
    container_name: node_express_api
    ports:
      - "5679:5679"
    volumes:
      - ./backends/node-express-api:/home/node/app
      - ./typings:/home/typings
    build:
      dockerfile: ./backends/node-express-api/Dockerfile
    command: >
      sh -c  "
        npm install && npm run dev
      "

  banquee_frontends:
    container_name: banquee_frontends
    ports:
      - "5680:5680"
    volumes:
      - ./frontends:/home/node/app
      - ./typings:/home/typings
    build:
      dockerfile: ./frontends/Dockerfile
    command: >
      sh -c  "
        npm install && npm run dev
      "